structure(list(url = "https://training.datim.org/api/dataStore/dataElementCadence/1997Q1", 
    status_code = 404L, headers = structure(list(date = "Thu, 20 Apr 2023 09:56:08 GMT", 
        `content-type` = "application/json;charset=UTF-8", `strict-transport-security` = "max-age=63072000;includeSubDomains", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `cache-control` = "no-cache, private", 
        vary = "accept-encoding", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(date = "Thu, 20 Apr 2023 09:56:08 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `strict-transport-security` = "max-age=63072000;includeSubDomains", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `cache-control` = "no-cache, private", 
            vary = "accept-encoding", `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_training.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "SESSION", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"httpStatus\":\"Not Found\",\"httpStatusCode\":404,\"status\":\"ERROR\",\"message\":\"Key '1997Q1' not found in namespace 'dataElementCadence'\"}"), 
    date = structure(1681984568, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 3e-05, pretransfer = 9.7e-05, starttransfer = 0.148211, 
    total = 0.148996)), class = "response")
